// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MtgInventoryManagementApi.MtgInventoryManagement.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MtgInventoryManagement.Data.Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260505134711_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MtgInventoryManagementApi.MtgInventoryManagement.Data.Models.Version", b =>
                {
                    b.Property<string>("version")
                        .HasColumnType("text");

                    b.HasKey("version");

                    b.ToTable("Version");
                });
#pragma warning restore 612, 618
        }
    }
}
