// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MtgInventoryManagementApi.MtgInventoryManagement.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MtgInventoryManagement.Data.Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260505163259_cards_migrations")]
    partial class cards_migrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MtgInventoryManagementApi.MtgInventoryManagement.Data.Models.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Alternative")
                        .HasColumnType("boolean");

                    b.Property<string>("Artist")
                        .HasColumnType("text");

                    b.Property<string>("Border")
                        .HasColumnType("text");

                    b.Property<int>("Cmc")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("ColorIdentity")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("ColorIndicator")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("Colors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Cost")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Finishes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Flavor")
                        .HasColumnType("text");

                    b.Property<string>("FrameVersion")
                        .HasColumnType("text");

                    b.Property<bool>("Funny")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasAlternativeDeckLimit")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("Keywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Loyalty")
                        .HasColumnType("integer");

                    b.Property<int>("MkmId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<string>("Power")
                        .HasColumnType("text");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Rebalanced")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ScryfallId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScryfallIllustrationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("StorySpotlight")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("Subtypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("Supertypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("TcgPlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<string>("Toughness")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Types")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("MtgInventoryManagementApi.MtgInventoryManagement.Data.Models.CardEdition", b =>
                {
                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<string>("EditionId")
                        .HasColumnType("text");

                    b.HasKey("CardId", "EditionId");

                    b.HasIndex("EditionId");

                    b.ToTable("CardEditions");
                });

            modelBuilder.Entity("MtgInventoryManagementApi.MtgInventoryManagement.Data.Models.Edition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Booster")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("CardCount")
                        .HasColumnType("integer");

                    b.Property<string>("KeyRuneCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Set")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Editions");
                });

            modelBuilder.Entity("MtgInventoryManagementApi.MtgInventoryManagement.Data.Models.ForeignName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Flavor")
                        .HasColumnType("text");

                    b.Property<int>("GathererId")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("ForeignNames");
                });

            modelBuilder.Entity("MtgInventoryManagementApi.MtgInventoryManagement.Data.Models.Legality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormatLegality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("Legalities");
                });

            modelBuilder.Entity("MtgInventoryManagementApi.MtgInventoryManagement.Data.Models.Version", b =>
                {
                    b.Property<string>("version")
                        .HasColumnType("text");

                    b.HasKey("version");

                    b.ToTable("Version");
                });

            modelBuilder.Entity("MtgInventoryManagementApi.MtgInventoryManagement.Data.Models.CardEdition", b =>
                {
                    b.HasOne("MtgInventoryManagementApi.MtgInventoryManagement.Data.Models.Card", "Card")
                        .WithMany("Editions")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MtgInventoryManagementApi.MtgInventoryManagement.Data.Models.Edition", "Edition")
                        .WithMany("CardEditions")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Edition");
                });

            modelBuilder.Entity("MtgInventoryManagementApi.MtgInventoryManagement.Data.Models.ForeignName", b =>
                {
                    b.HasOne("MtgInventoryManagementApi.MtgInventoryManagement.Data.Models.Card", null)
                        .WithMany("ForeignNames")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MtgInventoryManagementApi.MtgInventoryManagement.Data.Models.Legality", b =>
                {
                    b.HasOne("MtgInventoryManagementApi.MtgInventoryManagement.Data.Models.Card", null)
                        .WithMany("Legalities")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MtgInventoryManagementApi.MtgInventoryManagement.Data.Models.Card", b =>
                {
                    b.Navigation("Editions");

                    b.Navigation("ForeignNames");

                    b.Navigation("Legalities");
                });

            modelBuilder.Entity("MtgInventoryManagementApi.MtgInventoryManagement.Data.Models.Edition", b =>
                {
                    b.Navigation("CardEditions");
                });
#pragma warning restore 612, 618
        }
    }
}
